spring:
  application:
    name: delta-mini-bank

  datasource:
    url: jdbc:postgresql://localhost:5432/delta
    username: delta
    password: delta
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080